databases:
  - name: sunglass_DB
    databaseName: sunglass_db
    user: sunglass
    region: singapore

services:
  - type: web
    name: sunglass
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sunglass_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

